---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-exporter-secret
    namespace: infrastructure
type: Opaque
data:
    DATA_SOURCE_URI: cG9zdGdyZXNxbC5pbmZyYXN0cnVjdHVyZS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ==
    DATA_SOURCE_USER: YWRtaW4=
    DATA_SOURCE_PASS: QWRtaW4xMjM=