---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistent-volume-claim-nfs
  namespace: database
  labels:
    storageclass.storage.k8s.io: storage-nfs
    persistentvolumes.k8s.io: postgresql-persistent-volume-nfs
    persistentvolumeclaims.k8s.io: postgresql-persistent-volume-claim-nfs
spec:
  storageClassName: storage-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
# sudo chown -R 1001:1001 ./postgresql
# sudo chown -R 777 ./postgresql
