---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: infrastructure
type: Opaque
data:
    POSTGRES_PASSWORD: QWRtaW4xMjM=
# this password is a place holder base64 encoded, please change it in production