---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: infrastructure
data:
  username: cGdhZG1pbg== # base64 for "pgadmin"
  password: cGFnYWRtaW4tcGFzcw== # base64 for "pgadmin-pass"
type: Opaque

# kubectl create secret generic crossplane-aws-credentials --namespace=infrastructure --from-file=creds=./crossplane-aws-credentials.ini
