---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: infrastructure
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=
# kubectl create secret generic your-admin-secret-name --from-literal=admin-user=yourusername --from-literal=admin-password=yourstrongpassword
